### ISSUE TITLE
HEVC being deleted

### ISSUE THREAD

**Issue by 1977hud** [Collisionc/sickbeard_mp4_automator#17] opened 2019-03-26 03:24 UTC
I have a couple of old tv players that don't like x265 so I have been trying to convert everything with the script. But I have ran into the issue that when the script runs into HEVC x265 or HEVC 10 bit it will either rename the file to .original and move to the next file or it will encode to x264 then delete both files. I am using NVENC. on GTX1050ti. 
I couldn't find any information regarding this behavior and I'm not sure where the log files are or what to look for. FFMPEG on it's own converts them fine as does handbrake. Then the script will copy both the audio and video streams and add the metadata.

**Comment by Collisionc** [comment] 2019-03-27 22:13
I'll check it out, thanks for bringing it up.  

Can you post the [MP4] section of your autoprocess.ini file so I can test it out?

**Comment by 1977hud** [comment] 2019-03-28 05:17
Sure thing.. Here you go

[MP4]
ffmpeg = C:\ffmpeg\bin\ffmpeg.exe
ffprobe = C:\ffmpeg\bin\ffprobe.exe
threads = 0
output_directory = 
copy_to = 
move_to = 
output_extension = mp4
output_format = mp4
delete_original = false
relocate_moov = True
video-codec = nvenc_h264,h264_nvenc,h264,x264
video-bitrate = 15000
resolution-bitrate-restriction = 
video-max-width = 1920
qmin = 17
qmax = 
global_quality = 
maxrate = 25000
minrate = 
bufsize = 40000
nvenc_encoder_gpu = 0
nvenc_profile = 2
nvenc_preset = slow
nvenc_rate_control = vbr_hq
nvenc_temporal_aq = True
nvenc_weighted_prediction = False
nvenc_rc_lookahead = 32
enable_nvenc_decoder = False
enable_nvenc_hevc_decoder = False
nvenc_decoder_gpu = 0
nvenc_hevc_decoder_gpu = 0
h264-max-level = 4.1
use-qsv-decoder-with-encoder = False
enable_dxva2_gpu_decode = True
pix-fmt = nv12, yuv420p
quality = 
ios-audio = False
ios-first-track-only = False
ios-audio-filter = 
ios-move-last = False
max-audio-channels = 2
audio-codec = aac
audio-language = en
audio-default-language = en
audio-channel-bitrate = 256
audio-filter = 
audio-copy-original = False
audio-first-track-of-language = False
subtitle-codec = mov_text
subtitle-language = en
subtitle-default-language = en
subtitle-encoding = 
fullpathguess = True
convert-mp4 = True
tagfile = True
tag-language = en
download-artwork = Poster
download-subs = False
embed-subs = True
embed-only-internal-subs = True
sub-providers = addic7ed,podnapisi,thesubdb,opensubtitles
permissions = 0777
post-process = False
aac_adtstoasc = False
postopts = 
preopts = 
video-crf = 
use-hevc-qsv-decoder = False
video-profile = 
vsync = -1
burn_in_forced_subs = True
burn_in_full_subs = True
handle_m2ts_files = False
sample_rate = 
enable_hdr_sdr_tonemapping = False
enable_opencl_hdr_sdr_tonemapping = False
init_hw_device = opencl=gpu:0
forceconvert = False

**Comment by Collisionc** [comment] 2019-03-29 01:33
I'll definitely look into adding recycle bin support, because occasionally that would be useful for me as well. 

I have a few ideas of what might be happening, I'll commit a potential fix.

**Comment by Collisionc** [comment] 2019-03-29 01:35
I've been meaning to remove the qtfaststart requirement since ffmpeg can handle it, and it might have caused some weird issues in your situation.

Also, just in case, set nvenc_rc_lookahead to 0, as there is a nvidia driver bug that is crashing ffmpeg when using that with copy-back decoders like dxva2/nvdec. It might have been fixed by now, but I haven't checked it out in a while.

**Comment by 1977hud** [comment] 2019-03-29 02:44
Thanks, will give it a try when back home. Also, thanks for looking into the recyclebin. I have to use the recycle from cmdutils because there is now way to call the recyclebin from batch files, not sure with python, but the recycle.exe from cmdutils works great and sends them to the recyclebin.

**Comment by Collisionc** [comment] 2019-03-29 02:56
Yeah, relocate_moov = True -- I had added in ffmpeg's method of running qtfaststart a while ago and forgot to disable the original qtfaststart as it was no longer needed. It was possible that it is attempting to relocate the moov atom twice before, but now it will only do it once.

**Comment by 1977hud** [comment] 2019-03-29 03:00
Ok, I ran the script on a test file that was also being deleted. It still deleted both files if original delete was true. Here is the mediainfo file. It is not HEVC. It is AVC and MPEG audio, which is weird anyway. When I get back and can access my library I will try on the HEVC files.
[test file.txt](https://github.com/Collisionc/sickbeard_mp4_automator/files/3020914/test.file.txt)

**Comment by 1977hud** [comment] 2019-03-29 07:38
Ok after making the suggested changes, the HEVC convert but they are alot bigger. Original is 131mb converted is 359mb, would be nice to keep them smaller if there is a way. Also, the AVC file is still being deleted and watching it stalls at 43 converting and then jumps ahead in the script to try and tag but it has already deleted the file. Here is the HEVC media info and the index log where I ran it on both files.
[index.log](https://github.com/Collisionc/sickbeard_mp4_automator/files/3021551/index.log)
.
[hevc.txt](https://github.com/Collisionc/sickbeard_mp4_automator/files/3021532/hevc.txt)

**Comment by Collisionc** [comment] 2019-03-29 12:42
Have you tried setting nvenc_rc_lookahead=0  ?

**Comment by 1977hud** [comment] 2019-03-29 19:35
Yep, I made the two changes in the ini file to what you suggested above. 
relocate_moov = false
nvenc_rc_lookahead = 0

The couple of HEVC files I ran the script on converted fine but were 3 times the size of the original. 
I have several files from the AVC Test example I posted that still delete after making the changes. I can send you a test file if you have a prefered upload method, I have about 265 of them and they are around 80-100mb each.

**Comment by Collisionc** [comment] 2019-03-31 01:38
Email me a link to a couple of those files, whether it be onedrive, gdrive, etc. I'm having trouble reproducing this so far. 
s.alexlowery@gmail.com

**Comment by 1977hud** [comment] 2019-03-31 03:56
You should have a link to a shared folder in your email. Let me know if you need more. I added the smallest files of each problem that I could.

**Comment by Collisionc** [comment] 2019-03-31 04:13
Thanks got it, I'll check them out.

**Comment by 1977hud** [comment] 2019-03-31 04:17
No Problem, thanks for looking and trying to figure it out.

**Comment by Collisionc** [comment] 2019-03-31 05:06
Ok, able to reproduce... looks like it's due to something I added a long time ago to detect when ffmpeg starts to output warnings about "non-monotonous dts in output stream"

copy/paste from code comments I added with it:

`            # If the audio is being converted but the video is not, sometimes ffmpeg will spam warnings about 
            # how there is a "non-monotonous dts in output stream" -- This basically means that the sound is going
            # to be out of sync with the video and the only way to fix this it to re-encode the video along with the sound.
            # I don't feel like reorganizing everything to support sending the same file back through ffmpeg with different commands
            # Instead, we're going to close the current ffmpeg instance, and pipe the file through manual.py with a 
            # new option to force re-encoding.
            # The script will wait here until the subprocess is finished, in which it then exits this function and
            # pretends that everything is a-okay so that sabn/nzbget/etc scripts will properly autoimport the file.`

As mentioned, it opens up another manual.py process and forces the video stream to be encoded. Apparently, this is failing when the script is initiated with manual.py and a file that needs to be renamed .original. 

I'll add an option to disable this behavior, as it doesn't always mean the audio is out of sync... just sometimes.

**Comment by 1977hud** [comment] 2019-03-31 05:19
So it is probably more difficult to rename the .orginal back to .mp4 after the error and pipe it back through than to just have the option to disable it. At least I know I'm not crazy. LOL. Thanks for looking, just let me know how to proceed when you are ready. Any suggestions on the files that are triple the size of the originals? It's mainly x265 or xvid files that are converted to x264.

**Comment by Collisionc** [comment] 2019-03-31 05:20
As far as the size increases, that is to be expected when converting x265 to x264, to keep the same quality x264 will require a larger file. 

The one that you mentioned "doesn't delete but doubles", the file size increase is from the audio stream increasing in size.  audio-channel-bitrate = 256 -- this is probably too high, I set it to 128 for everything I do, but that's why the file size is increasing in that case.

**Comment by Collisionc** [comment] 2019-03-31 05:21
I ended up just disabling it all the time, as it's very rarely needed. Just pull the latest commit and it should work fine.

**Comment by 1977hud** [comment] 2019-03-31 05:22
Thanks, awesome work, I can't thank you enough.

**Comment by Collisionc** [comment] 2019-03-31 05:23
No problem, I'll properly fix it when I have some free time. :D Thanks for reporting.

**Comment by 1977hud** [comment] 2019-03-31 18:57
I did find another file that still deletes after the changes. It was just the 1 out of about 150 so far that I've processed. But it's x264 and AAC. Instead of just tagging it renames to original and fails to encode but doesn't delete original with it set to true in autoprocess.ini. 
I put it in the test folder I shared. I deleted the others but they may still show on your end. It is S04E20. I can manually encode it with ffmpeg so not a big deal. Just letting you know.

I am really interested in python can you tell me which file actually deletes the original so I can try to learn how to make it recycle? My current batch file works but I would like to recycle instead. Here is my current batch file, it processes each file and moves it with filebot into a folder structure and naming for Plex, then deletes any empty folders in the directory it's ran from.
SInce all my files have already been named with filebot it's fairly quick at moving.

for /R "%CD%\Original" %%i IN ("*.*") do (
              py -3 D:\Proc\manual.py -i "%%~fi" -a 
             "C:\Program Files\FileBot\filebot.exe" -rename "%%~dpni.mp4" -non-strict --format G:/TV/Converted/"{n}/{'Season '+s}/{n} - {s00e00} - {t}" --db TVDB --log info
              for /f "delims=" %%d in ('dir /s /b /ad ^| sort /r') do rd "%%d"
)
Pause

**Comment by Collisionc** [comment] 2019-04-01 22:43
It's attempting to burn in the subtitle stream and tripping on the comma in "Bob's"... I've had a lot of problems with commas and subtitle burn in, and I thought I had taken care of it, but I guess not!

**Comment by 1977hud** [comment] 2019-04-02 02:36
I didn't even think about the apostrophe, I tried without the exclamation mark and it still failed. I will remember that going forward. I've ran a few hundred more files and that is still the only one that gave me an issue. Thanks again.

**Comment by 1977hud** [comment] 2019-04-02 20:12
So, I changed my batch to name the files and folders on first stage with no apostrophe and then the automator ran and then my batch renamed them with the apostrophe and moved them to the finished folder. The only problem is that without the apostrophe it didn't tag the files with metadata and poster.

**Comment by Collisionc** [comment] 2019-04-02 22:23
I'm going to fix the script so that it works with apostrophes (whoops, called it a comma), it already does in 99% of cases, just not in this one case.

**Comment by 1977hud** [comment] 2019-04-02 23:19
Awesome, Thanks..

**Closed** 2020-07-16 15:03 UTC
